language: objective-c
os: osx
osx_image: xcode12
xcode_project: DPSystemVolumeController.xcodeproj

before_install:
  - gem install cocoapods xcpretty
  - set -o pipefail
  - xcodebuild clean -project DPSystemVolumeController.xcodeproj -scheme DPSystemVolumeController -sdk iphonesimulator | xcpretty -c

script:
  - pod lib lint
  - xcodebuild -project DPSystemVolumeController.xcodeproj -scheme DPSystemVolumeController -sdk iphonesimulator | xcpretty -c
