language: objective-c
osx_image: xcode7.1
xcode_project: DPSystemVolumeController.xcodeproj

before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
  - set -o pipefail
  - xcodebuild clean -project DPSystemVolumeController.xcodeproj -scheme DPSystemVolumeController -sdk iphonesimulator | xcpretty -c

script:
  - pod lib lint
  - xcodebuild -project DPSystemVolumeController.xcodeproj -scheme DPSystemVolumeController -sdk iphonesimulator | xcpretty -c
